CREATE CONSTRAINT domain_name_unique IF NOT EXISTS FOR (n:Domain) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT project_id_unique IF NOT EXISTS FOR (n:Project) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT project_slug_unique IF NOT EXISTS FOR (n:Project) REQUIRE n.slug IS UNIQUE;
CREATE CONSTRAINT topic_name_unique IF NOT EXISTS FOR (n:Topic) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT source_id_unique IF NOT EXISTS FOR (n:Source) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT source_url_unique IF NOT EXISTS FOR (n:Source) REQUIRE n.url IS UNIQUE;
CREATE CONSTRAINT document_id_unique IF NOT EXISTS FOR (n:Document) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT person_id_unique IF NOT EXISTS FOR (n:Person) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT organization_id_unique IF NOT EXISTS FOR (n:Organization) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT client_name_unique IF NOT EXISTS FOR (n:Client) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT location_id_unique IF NOT EXISTS FOR (n:Location) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT event_id_unique IF NOT EXISTS FOR (n:Event) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT finding_id_unique IF NOT EXISTS FOR (n:Finding) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT evidence_id_unique IF NOT EXISTS FOR (n:Evidence) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT note_id_unique IF NOT EXISTS FOR (n:Note) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT output_id_unique IF NOT EXISTS FOR (n:Output) REQUIRE n.id IS UNIQUE;
CREATE INDEX project_status_index IF NOT EXISTS FOR (n:Project) ON (n.status);
CREATE INDEX project_updated_index IF NOT EXISTS FOR (n:Project) ON (n.updatedAt);
CREATE INDEX source_url_index IF NOT EXISTS FOR (n:Source) ON (n.url);
CREATE INDEX source_kind_index IF NOT EXISTS FOR (n:Source) ON (n.kind);
CREATE INDEX source_status_index IF NOT EXISTS FOR (n:Source) ON (n.ingestionStatus);
CREATE INDEX finding_created_index IF NOT EXISTS FOR (n:Finding) ON (n.createdAt);
CREATE INDEX evidence_source_index IF NOT EXISTS FOR (n:Evidence) ON (n.sourceId);
CREATE INDEX evidence_document_index IF NOT EXISTS FOR (n:Evidence) ON (n.documentId);
CREATE CONSTRAINT publication_id_unique IF NOT EXISTS FOR (n:Publication) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT technology_id_unique IF NOT EXISTS FOR (n:Technology) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT researchquestion_id_unique IF NOT EXISTS FOR (n:ResearchQuestion) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT community_id_unique IF NOT EXISTS FOR (n:Community) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT timeperiod_id_unique IF NOT EXISTS FOR (n:TimePeriod) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT theme_id_unique IF NOT EXISTS FOR (n:Theme) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT culturalpractice_id_unique IF NOT EXISTS FOR (n:CulturalPractice) REQUIRE n.id IS UNIQUE;
MERGE (d:Domain {name:"technology"});
MERGE (d:Domain {name:"society"});
MERGE (d:Domain {name:"environment"});
MERGE (d:Domain {name:"esg"});
MERGE (d:Domain {name:"culture"});
MERGE (d:Domain {name:"business"});
MERGE (d:Domain {name:"other"});
